#!/usr/bin/env Python3
# -*- coding: utf-8 -*-
"""Larger string constants for CalcOPP-GUI.

CalcOPP – Calculation of One-Particle Potentials
CalcOPP-GUI – The Graphical User Interface of CalcOPP

This module declares larger strings constants (explanations, annotations, etc.)
that are used for documentation purposes in CalcOPP-GUI.
"""

__author__ = 'Dennis Wiedemann'
__copyright__ = 'Copyright 2019, Dennis Wiedemann'
__credits__ = ['Dennis Wiedemann']
__license__ = 'MIT'
__version__ = '2.0.0'
__maintainer__ = 'Dennis Wiedemann'
__email__ = 'dennis.wiedemann@chem.tu-berlin.de'
__status__ = 'Development'


CITATION = 'D. Wiedemann, CalcOPP, Calculation of One-Particle Potentials, Technische\n' \
           'Universität Berlin, Berlin (Germany), 2019, doi:XXX.'

LICENSE = 'CalcOPP is distributed under the ' + __license__ + ' license (see LICENSE file). It uses the module\n' \
          'PySimpleGUI by MikeTheWatchGuy distributed under the GNU General Public License\nv3.0 (see LGPL-3.0.txt).\n'

INTRODUCTION = 'Choose the source-data type by selecting a tab on the right. “2D PDF” and “3D PDF” can be generated ' \
               'after refinement with JANA2006, “Scatterer Density” is the result of MEM reconstruction with ' \
               'Dysnomia.\n\n' \
               'HERE BE DRAGONS: This is not a black-box tool. Know what you are doing and how to assess the ' \
               'sensibleness of your results! If you do not, this might be a good open-access read to start: ' \
               'D. Wiedemann et al., Z. Phys. Chem. 2017, 231, 1279–1302; doi:10.1515/zpch-2016-0918.\n\n'

ENDING = '\n\nAny file with the same name as the output file will be OVERWRITTEN WITHOUT ASKING! Be sure to save ' \
         'intermediate results that you are going to need.'

PDF2D = 'Input\n––––\n' \
        'The input must be an *.stf file generated by JANA2006 that contains the probability-density function (PDF) ' \
        'sampled on a uniform grid from a single section.\n\n' \
        'Options\n––––––\n' \
        '\n\n' \
        'Output\n–––––\n' \
        'The output is an ASCII file of space-separated x, y, PDF, and OPP values (both with errors, if supplied) ' \
        'for each grid point. You can plot it with several applications (e.g., gnuplot, QtiPlot, Origin, or Igor ' \
        'Pro).\n\n' \
        'Caveat\n––––––\n' \
        'For grid points with a non-positive PDF, arbitrarily huge OPPs and OPP errors of 10^9 meV are set. ' \
        'Nevertheless, this physically means a potential barrier of insurmountable height.'
# TODO: how to generate PDF (anharmonic refinement) and error file
# TODO: options to the right (Temperature, Include in Output)

PDF3D = 'Input\n––––\n' \
        'The input must be a temporary *_tmp.xsf file generated by JANA2006 that contains the probability-density ' \
        'function (PDF) sampled on a uniform grid. Only the first 3D data grid stored in the file is taken into ' \
        'account.\n\n' \
        'Options\n––––––\n' \
        '\n\n' \
        'Output\n–––––\n' \
        'The output is an *_opp.xsf file. All lines before and after the first 3D data grid are copied into it ' \
        'from the input verbatim. In addition, the file *_opp.vesta, which can be used to open the volumetric data ' \
        'in VESTA, is provided. Both files must be in the same directory for this to work.\n\n' \
        'In VESTA, you should switch off the displaying of sections, as the high OPP in most of the unit cell ' \
        'would obscure any area of interest. Choose the isosurface level (given in electronvolt) reasonably.\n\n' \
        'Caveat\n––––––\n' \
        'For grid points with a non-positive PDF, the highest finite OPP in the data (derived from the lowest ' \
        'positive PDF) is set to make the fringes of visualized isosurfaces less spiky after treatment with VESTA’s ' \
        'interpolation algorithm. If you further process the data or extract values directly, be aware that the ' \
        'potential barrier is insurmountably (infinitely) high at these points.'
# TODO: how to generate PDF (anharmonic refinement)
# TODO: options to the right (Temperature)

SD = 'Input\n––––\n' \
     '\n\n' \
     'Options\n––––––\n' \
     '\n\n' \
     'Output\n–––––\n' \
     '\n\n' \
     'Caveat\n––––––\n' \
     ''
# TODO: how to generate scatterer density (MEM reconstruction), comment on feasibility (with citation)
# TODO: what to do with output (VESTA)
# TODO: options to the right (Temperature, Extremal Value):
# '•  Minimum for Li, H (or even Ti or Mn) diffusion from neutron data if only one negative scatterer is ' \
# ' present\n' \
# '•  Maximum for all other atoms from neutron data if only one positive scatterer is present\n' \
# '•  Custom value (manually evaluated extremum in sensible, accessible area) for X-ray diffraction or ' \
# 'other cases'

MANUAL_PDF2D = INTRODUCTION + PDF2D + ENDING
MANUAL_PDF3D = INTRODUCTION + PDF3D + ENDING
MANUAL_SD = INTRODUCTION + SD + ENDING
